### ISSUE TITLE
[BUG] [[interface]

### ISSUE THREAD

**Issue by SimonBpvp** [JamminL/cata-classic-bugs#1064] opened 2024-04-29 17:33 UTC
![image](https://github.com/JamminL/cata-classic-bugs/assets/94299191/54fc326e-b5b0-4588-8880-635513c97497)

when you press escape it brings up the game menu and doesn't close the pvp pane
it should just close the pvp pane

**Comment by JamminL** [comment] 2024-04-29 18:22
Duplicate of https://github.com/JamminL/cata-classic-bugs/issues/1016

**Closed by JamminL** 2024-04-29 18:22 UTC
Labels: duplicate, Pending Approval, CATACLYSM
