### ISSUE TITLE
[BUG] "Hide character information" button state not retained upon reopening character panel

### ISSUE THREAD

**Issue by Avizurax7** [JamminL/cata-classic-bugs#1280] opened 2024-05-20 08:28 UTC
#### 1.1. Description

When using the "Hide Character Information" button on the character panel in the classic Cataclysm beta and pre-patch, the expected behavior is that the panel should retain its state (hidden or shown) when the character panel is closed and reopened. Currently, the state is not retained, causing the character information to be shown again upon reopening the panel.

  #### 1.2. How to Reproduce
  
          1. Open the character panel.
          2. Click the "Hide Character Information" button to hide the character information.
          3. Close the character panel.
          4. Reopen the character panel.
          
  #### 1.3  Source Material
  
  https://streamable.com/3nvrjo
  
### 2. Expected Behavior

The character information should remain hidden if it was hidden before the panel was closed.

  #### 2.2 Source Material

https://streamable.com/u8b862

**Comment by JamminL** [comment] 2024-05-20 19:05
Duplicate of https://github.com/JamminL/cata-classic-bugs/issues/964

**Closed by JamminL** 2024-05-20 19:04 UTC
Labels: duplicate, CATACLYSM
