### ISSUE TITLE
[BUG] [interface] no guild tab in spellbook (live patch)

### ISSUE THREAD

**Issue by SimonBpvp** [JamminL/cata-classic-bugs#1108] opened 2024-05-03 03:11 UTC
#### 1.1. Description
<img width="846" alt="image" src="https://github.com/JamminL/cata-classic-bugs/assets/94299191/bc26f16c-b776-4018-86b4-855d8dc3839f">
all my guild perks are in the general tab of the spell book
  #### 1.3  Source Material
{Video, Posts, etc..}
#### 2.1. Description
there was a little tab for all the guild perks 
![image](https://github.com/JamminL/cata-classic-bugs/assets/94299191/e6d1a88b-1e7b-422b-8a5f-194598c67912)

  #### 2.2 Source Material
https://www.youtube.com/watch?v=T4kNX4GdKsk

**Comment by JamminL** [comment] 2024-05-03 03:12
Duplicate of https://github.com/JamminL/cata-classic-bugs/issues/912

**Closed by JamminL** 2024-05-03 03:12 UTC
Labels: Pending Approval, CATACLYSM
