### ISSUE TITLE
[BUG] Extra layer of water above the sundering in stranglethorn vale

### ISSUE THREAD

**Issue by MannySJH** [JamminL/cata-classic-bugs#1201] opened 2024-05-10 18:34 UTC
#### 1.1. Description
Title
  #### 1.3  Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/168474168/0485ced2-d648-49d7-b024-c8e4412dc557)

### 2. Expected Behavior
![Northern-Stranglethorn-Vale---The-Sundering](https://github.com/JamminL/cata-classic-bugs/assets/168474168/5a6ec3f7-5db4-438c-8d4a-099ba431e5a7)

**Comment by CharWS** [comment] 2024-05-10 18:43
duplicate of https://github.com/JamminL/cata-classic-bugs/issues/979

**Closed by CharWS** 2024-05-10 18:43 UTC
Labels: Pending Approval, CATACLYSM
