### ISSUE TITLE
[BUG] Frost runes no working

### ISSUE THREAD

**Issue by Defeatedftw** [JamminL/cata-classic-bugs#1040] opened 2024-04-27 20:14 UTC
Frost rune should swap to death rune when you use festering strike but if you use icy touch instead of chains of ice before swapping the rune it doesnt work + vod of proof
https://www.youtube.com/watch?v=vzMIKKQRqMY

**Comment by CharWS** [comment] 2024-04-28 03:39
duplicate of https://github.com/JamminL/cata-classic-bugs/issues/886

**Closed by CharWS** 2024-04-28 03:39 UTC
Labels: Pending Approval, CATACLYSM
