### ISSUE TITLE
[BUG] Murder Was The Case They Gave Me bugged, cannot be completed

### ISSUE THREAD

**Issue by hypernormalisation** [JamminL/cata-classic-bugs#840] opened 2024-03-12 14:53 UTC
#### 1.1. Description
Quest [Murder Was The Case They Gave Me](https://www.wowhead.com/quest=26209/murder-was-the-case-that-they-gave-me) in westfall cannot be completed.

The various quest mobs the player can speak with do not give the appropriate clue quest credit when they are supposed to.

  #### 1.2. How to Reproduce
Head to Westfall and begin the quest. Talk to the NPCs until one does not attack the player.

  #### 1.3  Source Material
https://youtu.be/BHzr3JBpObg

#### 2.1. Description
When the player talks to one of the quest NPCs and asks them for information, either two things happen:
1. They attack the player
2. They give a "clue" advancing the quest credit.

  #### 2.2 Source Material
https://youtu.be/PcQLozc1jm4

**Comment by ForgeGit** [comment] 2024-03-12 17:27
Duplicate of https://github.com/JamminL/cata-classic-bugs/issues/827

**Closed** 2024-03-12 17:33 UTC
Labels: duplicate, General, CATACLYSM
