### ISSUE TITLE
Tranquilizing shot doesnt work w/o magic buff on enemy.

### ISSUE THREAD

**Issue by Kenniflopper** [JamminL/cata-classic-bugs#1039] opened 2024-04-27 19:43 UTC
#### 1.1. Description
Currently you cant use Tranquilizing shot on a target without any magic buffs
  #### 1.2. How to Reproduce
       Try to use Tranquilizing shot on a target without any magic buffs and notice that it simply doesnt go off.
  #### 1.3  Source Material
  https://youtu.be/GQ_nywvhT44
Its the same as this bug basicly -> https://github.com/JamminL/cata-classic-bugs/issues/931
#### 2.1. Description
You should be able to use tranquilizing shot on targets without any magic buffs, it will cost you focus and be used.

**Comment by JamminL** [comment] 2024-04-27 19:55
Duplicate of #931

**Closed by JamminL** 2024-04-27 19:55 UTC
Labels: Pending Approval, CATACLYSM
