### ISSUE TITLE
[BUG] Character sheet reverts to default settings every time it's closed

### ISSUE THREAD

**Issue by ssabbyccatt** [JamminL/cata-classic-bugs#1087] opened 2024-05-01 18:58 UTC
#### 1.1. Description
Currently, if you modify the order of your character sheet (for ex, move Spell category up, above melee & ranged categories) it will stay like that as long as you keep the character sheet open. The moment you close the character sheet, it reverts to the default order.
  #### 1.2. How to Reproduce
           1. Move any of the stats sections in your character sheet.
           2. Close the character sheet.
  #### 1.3  Source Material
https://github.com/JamminL/cata-classic-bugs/assets/99249505/c982d0fa-1b33-4566-a335-033a07a993b8
#### 2.1. Description
Character sheet should not revert to the default settings
  #### 2.2 Source Material
See retail character sheet implementation

**Comment by CharWS** [comment] 2024-05-01 18:59
duplicate of https://github.com/JamminL/cata-classic-bugs/issues/964

**Closed by CharWS** 2024-05-01 18:59 UTC
Labels: Pending Approval, CATACLYSM

**Comment by ssabbyccatt** [comment] 2024-05-01 19:04
> duplicate of #964

Damn, sorry, I searched to see if it was a dupe and that report did not come up.
