### ISSUE TITLE
[BUG] Character frame doesn't work properly on non-english clients

### ISSUE THREAD

**Issue by thehallowedfire** [JamminL/cata-classic-bugs#1133] opened 2024-05-04 14:04 UTC
### 1. Current Behavior
Character frame doesn't work on russian and german clients (clients with large number seperator "," (comma) instead of "." (dot)). Didn't check other non-english clients.
Also stat lines missing their backgrounds (should be bright stripes under each second line) but this is a common issue for any language clients.
And minor issue but I think should be pointed out (common issue for all clients): reputation frame is much wider than default collapsed character frame. They should have the same width.

  #### 1.1. Description
When you open character frame you get an error:
<details>
<summary>Error code</summary>

  ```lua
Message: ...dOns/Blizzard_CharacterFrame/Cata/PaperDollFrame.lua:1203: Usage: BreakUpLargeNumbers(number[, natural])
Time: Sat May  4 16:33:52 2024
Count: 1
Stack: ...dOns/Blizzard_CharacterFrame/Cata/PaperDollFrame.lua:1203: Usage: BreakUpLargeNumbers(number[, natural])
[string "=[C]"]: in function `BreakUpLargeNumbers'
[string "@Interface/AddOns/Blizzard_CharacterFrame/Cata/PaperDollFrame.lua"]:1203: in function `PaperDollFrame_SetAttackSpeed'
[string "@Interface/AddOns/Blizzard_CharacterFrame/Cata/PaperDollFrame.lua"]:171: in function `updateFunc'
[string "@Interface/AddOns/Blizzard_CharacterFrame/Cata/PaperDollFrame.lua"]:2780: in function `PaperDollFrame_UpdateStatCategory'
[string "@Interface/AddOns/Blizzard_CharacterFrame/Cata/PaperDollFrame.lua"]:2830: in function `PaperDollFrame_UpdateStats'
[string "@Interface/AddOns/Blizzard_CharacterFrame/Cata/PaperDollFrame.lua"]:2963: in function `PaperDoll_InitStatCategories'
[string "@Interface/AddOns/Blizzard_CharacterFrame/Cata/PaperDollFrame.lua"]:2233: in function <...dOns/Blizzard_CharacterFrame/Cata/PaperDollFrame.lua:2228>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Classic/UIParentPanelManager_Shared.lua"]:606: in function `SetUIPanel'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Classic/UIParentPanelManager_Shared.lua"]:451: in function `ShowUIPanel'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Classic/UIParentPanelManager_Shared.lua"]:319: in function <...PanelManager/Classic/UIParentPanelManager_Shared.lua:315>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Classic/UIParentPanelManager_Shared.lua"]:1095: in function `ShowUIPanel'
[string "@Interface/AddOns/Blizzard_CharacterFrame/Cata/CharacterFrame.lua"]:45: in function `ToggleCharacter'
[string "TOGGLECHARACTER0"]:1: in function <[string "TOGGLECHARACTER0"]:1>

Locals: (*temporary) = "2,20"
```
</details>

And because of this error some stat groups (like Melee, Spells, etc.) don't show up at all. Also your character model doesn't have background picture (should be specific picture for each race). Also if you close/open Character frame a few times, expand/collapse button will disappear because of this error:
<details>
<summary>Another error code</summary>

```lua
Message: [string "*CharacterFrame.xml:373_OnEnter"]:5: attempt to concatenate field 'expandTooltip' (a nil value)
Time: Sat May  4 16:33:55 2024
Count: 1
Stack: [string "*CharacterFrame.xml:373_OnEnter"]:5: attempt to concatenate field 'expandTooltip' (a nil value)
[string "*CharacterFrame.xml:373_OnEnter"]:5: in function <[string "*CharacterFrame.xml:373_OnEnter"]:1>

Locals: self = CharacterFrameExpandButton {
 0 = <userdata>
}
motion = true
(*temporary) = <function> defined =[C]:-1
(*temporary) = GameTooltip {
 SetBorderBlendMode = <function> defined @Interface/AddOns/Blizzard_SharedXML/SharedTooltipTemplates.lua:309
 NineSlice = Frame {
 }
 updateTooltip = 0.103000
 0 = <userdata>
 comparing = false
 TooltipBackdropOnLoad = <function> defined @Interface/AddOns/Blizzard_SharedXML/SharedTooltipTemplates.lua:278
 shoppingTooltips = <table> {
 }
 TopOverlay = Texture {
 }
 GetBackdropBorderColor = <function> defined @Interface/AddOns/Blizzard_SharedXML/SharedTooltipTemplates.lua:305
 layoutType = "TooltipDefaultLayout"
 needsReset = true
 BottomOverlay = Texture {
 }
 SetBackdropColor = <function> defined @Interface/AddOns/Blizzard_SharedXML/SharedTooltipTemplates.lua:293
 GetBackdropColor = <function> defined @Interface/AddOns/Blizzard_SharedXML/SharedTooltipTemplates.lua:297
 SetBackdropBorderColor = <function> defined @Interface/AddOns/Blizzard_SharedXML/SharedTooltipTemplates.lua:301
}
(*temporary) = ""
(*temporary) = nil
(*temporary) = ""
(*temporary) = "attempt to concatenate field 'expandTooltip' (a nil value)"
```
</details>

  #### 1.2. How to Reproduce
           1. Choose russian or german language and launch client
           2. Create a character and log on it
           3. Open character frame (default keybind C)
  #### 1.3  Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/112851853/018c29e3-3f6a-4b6a-8f4a-f5e0d9c72c66)
![image](https://github.com/JamminL/cata-classic-bugs/assets/112851853/44771a9b-457d-4282-8027-a55eafecca97)
![image](https://github.com/JamminL/cata-classic-bugs/assets/112851853/c2f381bf-db2f-4ea4-a2dc-3d43fb618627)

#### 2.1. Description
There should be all stat groups with stats on the right side when you expand the character frame and every second stat should have bright stripe under it. Also there should be background picture under character model.
  #### 2.2 Source Material
Should look like this:
![image](https://github.com/JamminL/cata-classic-bugs/assets/112851853/eb610b1f-4e47-4955-9449-ed94f80b5a32)

**Comment by CharWS** [comment] 2024-05-04 17:04
duplicate of https://github.com/JamminL/cata-classic-bugs/issues/1015

**Closed by CharWS** 2024-05-04 17:04 UTC
Labels: Pending Approval, CATACLYSM

**Comment by raethkcj** [comment] 2024-05-04 17:07
The missing stripes thing is new, albeit minor
