### ISSUE TITLE
[BUG] water ele invis in arena

### ISSUE THREAD

**Issue by SimonBpvp** [JamminL/cata-classic-bugs#1428] opened 2024-06-22 13:43 UTC
#### 1.1. Description
if you try to invis before the gates open as a frost mage, the water elemental pet will not get the invis buff, this exposes your location.
  #### 1.2. How to Reproduce

           1. enter arena
           2. summon water ele
           3. invis before the gates open
  #### 1.3  Source Material

#### 2.1. Description
the water ele should get the invis buff and be invisible just like the frost mage
  #### 2.2 Source Material
i watched Watchmeblink 1 but couldnt find a hard proof but I know something is definitely out there

**Comment by CharWS** [comment] 2024-06-22 13:45
duplicate of https://github.com/JamminL/cata-classic-bugs/issues/1068

**Closed by CharWS** 2024-06-22 13:45 UTC
Labels: duplicate, CATACLYSM
