### ISSUE TITLE
[BUG] [Death Knight] Dark Simulacrum interaction with Ice block maybe other spells?

### ISSUE THREAD

**Issue by Heroclassx** [JamminL/cata-classic-bugs#1136] opened 2024-05-04 15:38 UTC
### 1. Current Behavior
https://clips.twitch.tv/ComfortableNastySeahorseDAESuppy-pBgtlOGNPWqL93sr

When using dark simulacrum on a mage which then blocks, you will not be able to use the copied ice block sicne it costs mana.
  #### 1.1. Description
"Places a dark ward on an enemy that persists for 8 sec, triggering when the enemy spens mana on a spell, and allowing the death knight to unleash an exact duplicate of that spell. Against nonplayers, only absorbs some harmful spells. 

  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Use Dark simulacrum in a duel against mage
           2. make the mage use ice block
           3. check cost of the spell and watch not being able to use it
           4. 
  #### 1.3  Source Material
[[[{Video, Posts, etc..}](https://clips.twitch.tv/ComfortableNastySeahorseDAESuppy-pBgtlOGNPWqL93sr)]

### 2. Expected Behavior
it should not cost mana

**Comment by CharWS** [comment] 2024-05-04 17:06
duplicate of https://github.com/JamminL/cata-classic-bugs/issues/940

**Closed by CharWS** 2024-05-04 17:06 UTC
Labels: Pending Approval, CATACLYSM
