### ISSUE TITLE
[BUG] #somechanges - It is currently impossible to obtain Heroic Tier Shoulders and Helm without doing Normal Mode Raids

### ISSUE THREAD

**Issue by Yotsutester** [JamminL/cata-classic-bugs#1264] opened 2024-05-18 03:46 UTC
I found out today that there is no way to bypass the Heroic Mode Tier piece requirements. For each Heroic Tier Item, you have to turn in a Normal Mode Tier Item + a Heroic Tier Token or Al'akir Token. The two Tier items that are unobtainable with Valor are Helm and Shoulder. The tokens only drop from a raid.

This system would force you to run Normal Mode Raids in order to get your Heroic Tier.

Please change or clarify the intention since you cannot run both Normal and Heroic on the same lockout.

**Comment by CharWS** [comment] 2024-05-18 03:48
duplicate of https://github.com/JamminL/cata-classic-bugs/issues/1198

**Closed by CharWS** 2024-05-18 03:48 UTC
Labels: Pending Approval, CATACLYSM
