### ISSUE TITLE
[BUG] Fresh 80 Level Death Knight has too many talents

### ISSUE THREAD

**Issue by Kilimandaros** [JamminL/cata-classic-bugs#922] opened 2024-03-30 06:31 UTC
#### 1.1. Description
Death Knights have 38 talent points at level 80 (at least when made using template character).
  #### 1.2. How to Reproduce
           1. Create fresh level 80 Death Knight.
           2. Open talent tree.
           3. Choose any specialisation.
           4. You have 38 talents to spend.
  #### 1.3  Source Material
![WoWScrnShot_033024_071743](https://github.com/JamminL/cata-classic-bugs/assets/27138041/c8c9ee62-5d89-496b-adca-9dc3eecc32b9)
#### 2.1. Description
Everyone should have 36 talent points at level 80. You get one at level 10, one at level 11 and afterwards every second level you get a talent point. So at level 80 (79) one should have 36 talent points. Which means that after getting one at every level from 81 onwards, we end up with 41 talents when we hit 85. Other classes have 36 as well.
  #### 2.2 Source Material
![WoWScrnShot_033024_071720](https://github.com/JamminL/cata-classic-bugs/assets/27138041/88ccb5d8-3d7e-4699-bc40-8230192dde7b)

**Comment by lordblackadder** [comment] 2024-03-30 15:41
This also happens with:
- DKs leveled from 55 to 80 during beta
- Copied lvl 80 DKs

**Comment by Aggrend** [comment] 2024-04-29 19:59
I believe this should be fixed as of last week on beta/ptr.

**Comment by JamminL** [comment] 2024-04-29 20:03
![image](https://github.com/JamminL/cata-classic-bugs/assets/107503518/67408b21-f550-4306-af3d-5f6ca6c94e4d)

Template DK character on beta

**Comment by Aggrend** [comment] 2024-04-29 21:07
Ah I see what the issue is. We had sent out two hotfixes to fix this but one of them is a code hotfix which requires restarts. Going to see if we can get a restart here in a bit to pick that fix up.

**Comment by JamminL** [comment] 2024-04-29 21:41
Fixed now!

**Closed by JamminL** 2024-04-29 21:41 UTC
Labels: Death Knight, BUG, Fixed, CATACLYSM
