### ISSUE TITLE
[BUG] glyph of blind vs piercing shots

### ISSUE THREAD

**Issue by SimonBpvp** [JamminL/cata-classic-bugs#1274] opened 2024-05-19 11:05 UTC
#### 1.1. Description
glyph of blind doesn't remove hunter deep wounds (piercing shots)
  #### 1.2. How to Reproduce
         
           1. crit the target with hunter
           2. blind the target with rogue
  #### 1.3  Source Material
https://clips.twitch.tv/WiseScrumptiousClipsmomKlappa-_IkCpbRuMjPOMGZN

**Comment by JamminL** [comment] 2024-05-19 11:06
Duplicate of https://github.com/JamminL/cata-classic-bugs/issues/1249

**Closed by JamminL** 2024-05-19 11:06 UTC
Labels: duplicate, Pending Approval, CATACLYSM
