### ISSUE TITLE
Dispell is not dispelling unless there is a debuff / buff on target [BUG]

### ISSUE THREAD

**Issue by oldspices** [JamminL/cata-classic-bugs#1203] opened 2024-05-10 23:18 UTC
#### 1.1. Dispell is not dispelling or going through unless there is a debuff / buff on target
{Describe how that mechanic/spell/npc is currently working, in detail}
  #### 1.2. Dispell is not dispelling unless there is a debuff / buff on target
          {Describe the steps to reproduce the particular bug, in detail:
           1. press any dispell / sooth etc with no buffs / debuffs on target- 
           2. notice it not go off
           3.   #### 1.3  Source Material
{Video, Posts, etc..}
#### 2.1. Description
{Describe how that mechanic/spell/npc should be working, in detail}
  #### 2.2 Source Material
{Video, Posts, etc..}

**Comment by AidanZMoon** [comment] 2024-05-10 23:19
Duplicate of this issue https://github.com/JamminL/cata-classic-bugs/issues/931

**Closed** 2024-05-10 23:20 UTC
Labels: duplicate, CATACLYSM
