### ISSUE TITLE
[#SomeChanges Suggestion] Bringing a Blizzard fix forward regarding Hunter pets

### ISSUE THREAD

**Issue by perpabc** [JamminL/cata-classic-bugs#1173] opened 2024-05-07 18:15 UTC
https://www.bluetracker.gg/wow/topic/us-en/10859655954-dismiss-pet-nerf/

According to Blizzard in 2013, Hunters were unintentionally able to bypass pet cooldowns by dismissing/resummoning their pets. Other pet classes were fixed in 2011, with Hunters remaining - the blue post above confirms that this wasn't intentional at least at the time in 2013. Read into this how you will, and whether this was an oversight by Blizzard in Cata, or if it was intentional. It would be helpful to be in contact with anyone from Blizzard back then, to understand this further. 

**Pain Points:**  
Hunters are the only pet class that can have multiple pets, that are;
1. Almost unkillable [mend pet/wall]
2. Uncontrollable [pvp trinket]
3. Able to CC on demand
4. Able to use Roar of Sacrifice on demand, **which halves the damage of most classes**

If a pet's close to dying or has used cds, the Hunter can Dismiss Pet in 2 seconds, an _uninterruptable_ cast and summon a new one, with all cds/health reset. 

The fix to Earthbind root in Wrath to give it Diminishing Returns more recently, and the fix to Shadowmeld in 2022 are great examples of unintentional bugs being smoothed out for Classic, and we'd argue this pet mechanic is more desperately in need of the fix it was given years ago.

References of other classes pets being resummoned and their cds not being reset after fixes:
Mage: https://youtu.be/AaULqV0kMO0?t=140 (June 2012, water ele freeze not reset on resummon)
Warlock: https://youtu.be/iX5XvCrC9Dw?t=410 (April 2012, Spell lock not reset on pet resummon with Soulburn)
Warlock 2: https://youtu.be/cYNiMtU9MAY?t=410 (August 2012, Spell lock not reset with Demonic Rebirth talent either)

**Comment by CharWS** [comment] 2024-05-07 18:21
duplicate of #1076

**Closed by CharWS** 2024-05-07 18:21 UTC
Labels: #SomeChanges Suggestion
