### ISSUE TITLE
[BUG] Pet's abilities are only reset on wipe if the pet died first

### ISSUE THREAD

**Issue by brave-goose** [JamminL/cata-classic-bugs#1406] opened 2024-06-12 22:07 UTC
#### 1.1. Description
Pet abilities only reset if the pet dies first, which doesn't happen very often even if you try to die after the pet. Abilities such as Call of the Wild are main 5 minute cooldowns and should be reset after every wipe regardless of who died first.  
#### 1.2. How to Reproduce
           1. During a raid boss fight, use a pet ability with a long cooldown, such as Call of the Wild.
           2. Die before the pet (as usual)
           3. After a wipe, see that all abilities except the pet's ability have been reset
  #### 1.3  Source Material
#### 2.1. Description
All abilities must be reset, including pet abilities regardless of who died first
  #### 2.2 Source Material

**Comment by CharWS** [comment] 2024-06-12 22:31
duplicate of https://github.com/JamminL/cata-classic-bugs/issues/1268

**Closed by CharWS** 2024-06-12 22:31 UTC
Labels: duplicate, CATACLYSM
