### ISSUE TITLE
[BUG] [interface] Place in Bags

### ISSUE THREAD

**Issue by SimonBpvp** [JamminL/cata-classic-bugs#1311] opened 2024-05-24 16:27 UTC
![image](https://github.com/JamminL/cata-classic-bugs/assets/94299191/d13102f3-91bb-416a-b55c-7bcb39b79eb4)

this button on char pane doesn't work, you cant use it to send the gear to your bag.

**Comment by JamminL** [comment] 2024-05-24 16:27
Duplicate of https://github.com/JamminL/cata-classic-bugs/issues/966

**Closed by JamminL** 2024-05-24 16:27 UTC
Labels: duplicate, Pending Approval, CATACLYSM
