### ISSUE TITLE
[BUG] [item] enchant scrolls don't work (wrong level)

### ISSUE THREAD

**Issue by SimonBpvp** [JamminL/cata-classic-bugs#1061] opened 2024-04-29 16:06 UTC
![WoWScrnShot_042924_170414](https://github.com/JamminL/cata-classic-bugs/assets/94299191/576eb4c7-dc0a-4881-90a4-4baefeaf1770)

error message states: Target is too low level. 
but the target item is level 346 so a cataclysm enchant should work on it

**Comment by CharWS** [comment] 2024-04-29 16:07
duplicate of https://github.com/JamminL/cata-classic-bugs/issues/1022

**Closed by CharWS** 2024-04-29 16:07 UTC
Labels: Pending Approval, CATACLYSM
