### ISSUE TITLE
[BUG] Ghoul using all engery

### ISSUE THREAD

**Issue by Woffl8** [JamminL/cata-classic-bugs#1337] opened 2024-05-29 05:19 UTC
#### 1.1. Description
DK Ghoul is spending all of its energy when claw has auto cast toggled on.
This prevent use of any other ability when needed if the energy is drained.

On Wotlk, MoP and WotLK classic. your ghoul will only spend its energy on Claw when energy is 70 or above.
DK's would macro pet claw into abilities for PvE to spend the extra energy.
 
#### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Enable Autocast on Claw
           2. Attack and watch energy

#### 2.1. Description
Ghoul will only autocast claw when 70 energy or above.
 
#### 2.2 Source Material
This is clearly a bug/oversight in actual Cata as it works correctly in OG WotLK, Mop and WotLK classic.

**Comment by CharWS** [comment] 2024-05-29 05:21
duplicate of https://github.com/JamminL/cata-classic-bugs/issues/1132

**Closed by CharWS** 2024-05-29 05:21 UTC
Labels: Pending Approval, CATACLYSM
