### ISSUE TITLE
[BUG] Warlock pet does not refresh cooldowns on resummon

### ISSUE THREAD

**Issue by OverlordDeveloper** [JamminL/cata-classic-bugs#1407] opened 2024-06-12 23:33 UTC
#### 1.1. Description

When you summon a new demon, its spells should be reset.

  #### 1.2. How to Reproduce

           1. Summon any demon
           2. use its abilities
           3. summon the demon again, either with soulburn, demonic rebirth or just summon it normally
           4. the abilities do not refresh their cd's

#### 2.1. Description

Once you summon a new demon the spells should reset. 

  #### 2.2 Source Material
Check this video -> Snutz 5 at  5:55 or 9:00, the felhunter has both silence and shadow bite on cooldown, he summons a new pet and they reset. 

[reference video](https://youtu.be/7ibtrZdtJB8?t=353)

**Comment by CharWS** [comment] 2024-06-12 23:36
duplicate of https://github.com/JamminL/cata-classic-bugs/issues/1172

**Closed by CharWS** 2024-06-12 23:36 UTC
Labels: duplicate, CATACLYSM

**Comment by SimonBpvp** [comment] 2024-06-13 05:13
Not an exact duplicate, this is about lock pets but also, not a bug.
They hotfixed this for lock pets during s11, it only worked before the hotfix. The footage in snutz 5 is from before the hotfix. 
There isn't any documentation for this, the only thing I found is old AJ posts after the hotfix. 
![image](https://github.com/JamminL/cata-classic-bugs/assets/94299191/86f59baa-ea9c-4dd7-998f-630d0462dfcd)
https://web.archive.org/web/20120221010117/http://www.arenajunkies.com/topic/219700-fel-dom-cs/
https://web.archive.org/web/20120222132728/http://www.arenajunkies.com/topic/219709-soul-burn-spell-lock-hotfix/

**Comment by AidanZMoon** [comment] 2024-06-13 06:59
This was 100% a bug. The internal documentation on it says this was happening because when a pet was summoned it almost instantly had Arena Preparation applied to and removed from it.

That's why this was only happening in RBGs and Arena where lock pets had cooldowns reset on summon. And also why when this bug was fixed it did not also fix Hunter pet CD. Because they were different issues.

**Comment by SimonBpvp** [comment] 2024-06-13 21:27
I have caused confusion here sorry, I said 'not a bug' meaning OP's report is not a bug.
