### ISSUE TITLE
[BUG] Character sheet stats panel doesn't stay open 

### ISSUE THREAD

**Issue by TeaDrinkingDragon** [JamminL/cata-classic-bugs#1208] opened 2024-05-11 16:14 UTC
#### 1.1. Description
The "Show Character Information" tab on the Char sheet doesn't stay open when you 
{Describe how that mechanic/spell/npc is currently working, in detail}
  #### 1.2. How to Reproduce
1. Open the Charsheet 
2. Click "Show Character Information" on the bottom right 
3. Close and re-open your Charsheet        

This behaviour can be observed in the video below.
  #### 1.3  Source Material
https://youtu.be/kA5C33AX1KI
#### 2.1. Description
The Information tab should open automatically if toggled, without having to click it again every time you open your Charsheet.
Correct behaviour can be observed in the video below.
  #### 2.2 Source Material
https://youtu.be/kxRoJ1rYVYE?si=HWM_ds6Okns8zmUy&t=368

**Comment by CharWS** [comment] 2024-05-11 16:20
duplicate of #964

**Closed by CharWS** 2024-05-11 16:20 UTC
Labels: duplicate, CATACLYSM
