### ISSUE TITLE
[BUG] [live realms] guards attack you when you zone into moonglade / gadgetzan

### ISSUE THREAD

**Issue by SimonBpvp** [JamminL/cata-classic-bugs#1283] opened 2024-05-21 08:12 UTC
### 1. Current Behavior
when u teleport to moonglade or gadgetzan, maybe other neutral areas that have guards too, the guards will attack you as if you just attacked an enemy player. It happens when taking a portal or leaving a dungeon. 50% chance in my experience.

**Comment by CharWS** [comment] 2024-05-21 15:19
duplicate of https://github.com/JamminL/cata-classic-bugs/issues/1113

**Closed by CharWS** 2024-05-21 15:19 UTC
Labels: Pending Approval, CATACLYSM
