### ISSUE TITLE
[BUG]Minimap Tracking function missing settings

### ISSUE THREAD

**Issue by Snipin** [JamminL/cata-classic-bugs#1292] opened 2024-05-22 12:51 UTC
#### 1.1. Description
Tracking Function for the minimap is currently missing the ability to track Target, Focus, and Quest POI

  #### 1.2. How to Reproduce
           1. Open Tracking
           2. Attempt to find Target, Focus, or Quest POI tracking
           3. Cry
          
  #### 1.3  Source Material
(https://i.imgur.com/iKOHW9U.png)

#### 2.1. Description
Minimap Tracking interface seems to be using the WOTLK version, rather than the Cataclysm version that you can see in the following Screenshot.

  #### 2.2 Source Material
(https://i.imgur.com/2uGhjul.png)

**Comment by JamminL** [comment] 2024-05-22 12:54
Duplicate of https://github.com/JamminL/cata-classic-bugs/issues/913

**Closed by JamminL** 2024-05-22 12:54 UTC
Labels: duplicate, CATACLYSM
