### ISSUE TITLE
[BUG]Unholy Frenzy does not break Repentance

### ISSUE THREAD

**Issue by Snipin** [JamminL/cata-classic-bugs#1356] opened 2024-06-01 15:23 UTC
#### 1.1. Description
Unholy Frenzy is not breaking Repentance
  #### 1.2. How to Reproduce
           1. Apply Unholy Frenzy
           2. Have Ret Paladin cast Repentance on target with Unholy Frenzy
           3. Notice the Repentance does not break
  #### 1.3  Source Material
https://streamable.com/c4elqy
  #### 2.1. Description
Unholy Frenzy breaks all CC that is broken upon damage. However, currently Repentance is not broken by it.

**Comment by SimonBpvp** [comment] 2024-06-02 01:22
Is it definitely a bug?

**Comment by AidanZMoon** [comment] 2024-06-09 09:00
This is accurate to 4.3.4.
Repentance does not break on Unholy Frenzy, Spirit Link Totem, or Death and Decay.
This is how it was in OG Cataclysm as well

**Comment by Snipin** [comment] 2024-06-09 09:02
> This is accurate to 4.3.4. Repentance does not break on Unholy Frenzy, Spirit Link Totem, or Death and Decay. This is how it was in OG Cataclysm as well

whats the likelihood of getting this changed if I make a somechanges report?
I feel like certain CCs not breaking to certain damage is very unintuitive

**Comment by AidanZMoon** [comment] 2024-06-09 09:30
Highly, highly, unlikely.

Unholy Frenzy breaking Repentance is accurate to 4.3.4 AND -> Unholy Frenzy broke almost all effects during Cataclysm except for a small few, but checking our historical records and bugs, it was actually supposed to not break ANY CC.

Was reported 12 years ago, and then finally worked on in 5.1 and release in 5.2 - 5.3 they added even more CC's to the list that Unholy Frenzy doesn't break.
So it was a 'bug' that it broke anything, which was fixed in Pandaria.
So Repentance not breaking on Unholy Frenzy is actually correct behavior and intended behavior.
Unholy Frenzy breaking other CC's is correct to reference behavior, but actually unintended behavior.

![image](https://github.com/JamminL/cata-classic-bugs/assets/137581830/0f326b1d-df24-4a93-9b1c-eab9ff5e8804)
"Blind/Paralyze/Repentance/Polymorph/Freezing Trap now stay active while Unholy Frenzy is active"

**Comment by Heroclassx** [comment] 2024-06-09 09:45
I disagree with the statement that it was a bug during cataclysm, in MOP (where the hotfix went live) Holinka was hired as a PVP-Dev, when he got hired he went on twitter and tweeted at the pvp playerbase and asked for what should get changed to make the game better. Hydramist/Hydra said that he thinks unholy frenzy breaking cc seems very annoying (even tho unholy frenzy is easily avoidable by just dispelling it by any rogue/hunter/druid. 

Holinka then changed it after Hydra said it, this whole conversation is still on twitter

**Comment by Snipin** [comment] 2024-06-09 09:50
> Highly, highly, unlikely.
> 
> Unholy Frenzy breaking Repentance is accurate to 4.3.4 AND -> Unholy Frenzy broke almost all effects during Cataclysm except for a small few, but checking our historical records and bugs, it was actually supposed to not break ANY CC.
> 
> Was reported 12 years ago, and then finally worked on in 5.1 and release in 5.2 - 5.3 they added even more CC's to the list that Unholy Frenzy doesn't break. So it was a 'bug' that it broke anything during Cataclysm, which was fixed in Pandaria. So Repentance not breaking on Unholy Frenzy is actually correct behavior and intended behavior. Unholy Frenzy breaking other CC's is correct to reference behavior, but actually unintended behavior.
> 
> ![image](https://private-user-images.githubusercontent.com/137581830/337961699-0f326b1d-df24-4a93-9b1c-eab9ff5e8804.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MjY4OTYsIm5iZiI6MTcxNzkyNjU5NiwicGF0aCI6Ii8xMzc1ODE4MzAvMzM3OTYxNjk5LTBmMzI2YjFkLWRmMjQtNGE5My05YjFjLWVhYjlmZjVlODgwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQwOTQ5NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjIxYzE4ZjE1MDc1MjlhYTdmZGYwOTUwOWIyYzRjMmM0NTk2NGNjM2NhZjYxOTBjMjM4YzQ1M2YyZTNkNWNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AnDalVK0IsowbVbxEls1xmGksV2hkLupeyY-fARGtks) "Blind/Paralyze/Repentance/Polymorph/Freezing Trap now stay active while Unholy Frenzy is active"

Unholy Frenzy was made to not break CC anymore after it was made undispellable

**Comment by AidanZMoon** [comment] 2024-06-09 10:21
> I disagree with the statement that it was a bug during cataclysm, in MOP (where the hotfix went live) Holinka was hired as a PVP-Dev, when he got hired he went on twitter and tweeted at the pvp playerbase and asked for what should get changed to make the game better. Hydramist/Hydra said that he thinks unholy frenzy breaking cc seems very annoying (even tho unholy frenzy is easily avoidable by just dispelling it by any rogue/hunter/druid.
> 
> Holinka then changed it after Hydra said it, this whole conversation is still on twitter

If you have a link to it that would be great. Can't seem to find it easily.

I will say I don't want my superfluous details in my explanation to distract, and don't want to get tied down in semantics or bug vs. intended vs. not bug.

What it comes down to is this behavior is true to reference and was never reported as a bug then, and the behavior was never changed to not to this later on. So the current state of Unholy Frenzy is not bugged when it comes to Repentance, and is working as intended with Repentance.

**Closed** 2024-06-09 13:24 UTC
Labels: Paladin, Death Knight, Not a Bug, CATACLYSM
