### ISSUE TITLE
[BUG] Horde Hearthstones change to Valley of Strength after relogging

### ISSUE THREAD

**Issue by rahged** [JamminL/cata-classic-bugs#858] opened 2024-03-15 05:47 UTC
#### 1.1. Description
Horde hearthstones are taking characters to Orgrimmar regardless of race/starting zone.
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Create a new Horde character. Hearthstone will indicate the correct starting zone.
           2. Log out
           3. Log back in. Hearthstone will now show as Valley of Strengthb
  #### 1.3  Source Material
Hearthstone location showing KTC Headquarters on a brand new toon
![image](https://github.com/JamminL/cata-classic-bugs/assets/65062699/b7f02110-376e-41e4-a0dd-661de9f167cf)

Hearthstone location showing Valley of Strength after logging out and back in
![image](https://github.com/JamminL/cata-classic-bugs/assets/65062699/c1edfb9c-c3b5-4d45-b883-16dbaf65ff8e)

Replicated with Blood Elves
![image](https://github.com/JamminL/cata-classic-bugs/assets/65062699/857782fb-5406-4e90-8777-b9b4d4a6eaa5)
![image](https://github.com/JamminL/cata-classic-bugs/assets/65062699/73889072-2ba0-47dd-a32b-c0373ecdd8e3)

Replicated with Trolls
![image](https://github.com/JamminL/cata-classic-bugs/assets/65062699/085b9c89-5c8f-4d65-9510-1e380dc8c584)
![image](https://github.com/JamminL/cata-classic-bugs/assets/65062699/a930f30d-3930-478e-b7a1-95edcc7b650e)

Replicated with Tauren
![image](https://github.com/JamminL/cata-classic-bugs/assets/65062699/5acd69da-c4c4-415b-982c-a19519d16ffe)
![image](https://github.com/JamminL/cata-classic-bugs/assets/65062699/3031f6ae-0656-46e9-8b54-6a5921196edf)

Replicated with Orcs
![image](https://github.com/JamminL/cata-classic-bugs/assets/65062699/a8b8611b-d683-40d8-9cbf-1b552f39d29f)
![image](https://github.com/JamminL/cata-classic-bugs/assets/65062699/c4bd3295-79d7-4f6f-9464-8abccbc63dc5)

#### 2.1. Description
Hearthstone should stay as the original location until a new location is set
  #### 2.2 Source Material

Forsaken are staying at the same location after relogging several times. 
![image](https://github.com/JamminL/cata-classic-bugs/assets/65062699/52a53c5c-d3c2-4c20-90f2-81076a4b7773)
![image](https://github.com/JamminL/cata-classic-bugs/assets/65062699/26ca4cb1-ecd0-432b-b132-389624e13d6d)

**Comment by ForgeGit** [comment] 2024-03-15 09:14
Duplicate of https://github.com/JamminL/cata-classic-bugs/issues/824

**Closed** 2024-03-15 10:32 UTC
Labels: duplicate, General, CATACLYSM
