### ISSUE TITLE
[BUG] Boomkin base spirit converting to hit

### ISSUE THREAD

**Issue by ssabbyccatt** [JamminL/cata-classic-bugs#954] opened 2024-04-10 19:07 UTC
#### 1.1. Description
Base spirit is converting to hit rating
  #### 1.2. How to Reproduce
           1. Unequip all gear with Balance of Power talent 2/2
           2. Check stats page
  #### 1.3  Source Material
https://cdn.discordapp.com/attachments/1171267821112676363/1227695253604008006/Screenshot_2024-04-10_150214.png?ex=6629574d&is=6616e24d&hm=8c17e4fa187099adae0fcb5ce57758c4eb67f7941e5fed3195d60ec65e0a1b00&
#### 2.1. Description
Only spirit from items etc should convert to hit, base spirit should not.
  #### 2.2 Source Material
https://cdn.discordapp.com/attachments/1225070520542826568/1227696175830929518/Screenshot_2024-04-10_150546.png?ex=66295829&is=6616e329&hm=3dead3635aa4b4141428dc59ec7d266b2b8ee10d76f79f621215b8ae693c430b&
Additionally, both Rawr and SimulationCraft from Cata do not include base spirit in their hit conversions.

**Comment by lordblackadder** [comment] 2024-04-10 20:36
Can confirm Elemental also has this issue (plus the percentages are off)
![image](https://github.com/JamminL/cata-classic-bugs/assets/12127284/585294b7-25ca-40ad-89a0-fea5ce2978fc)

**Comment by raethkcj** [comment] 2024-04-10 22:27
This is a duplicate of #861 although it's good to note it affects all three classes

**Closed** 2024-04-10 22:29 UTC
Labels: duplicate, Shaman, Druid, Priest, CATACLYSM
