### ISSUE TITLE
[BUG] glyph tab disapppears

### ISSUE THREAD

**Issue by SimonBpvp** [JamminL/cata-classic-bugs#1427] opened 2024-06-22 13:39 UTC
#### 1.1. Description
Not sure if this site is still alive but anyway, I was levelling a pala and the glyph tab would appear on reload but then disappear whenever you click it.
  #### 1.2. How to Reproduce
           1. level a pala or maybe any class to 10
           2. open talent pane
           3. try to click the glyph pane
  #### 1.3  Source Material
<img width="340" alt="Screenshot 2024-06-22 at 14 36 46" src="https://github.com/JamminL/cata-classic-bugs/assets/94299191/e0e6886b-9311-4fd0-9345-84c2eeb184bf">
<img width="436" alt="Screenshot 2024-06-22 at 14 36 58" src="https://github.com/JamminL/cata-classic-bugs/assets/94299191/65765db8-8d75-4eb8-a360-e0617d3d8d02">

#### 2.1. Description
it should probably only be showing if there is a possibility of clicking on it

**Comment by raethkcj** [comment] 2024-06-23 13:37
Duplicate of #826

**Closed by raethkcj** 2024-06-23 13:37 UTC
Labels: Pending Approval, CATACLYSM
