### ISSUE TITLE
[BUG] [Interface] scrolling through glyphs

### ISSUE THREAD

**Issue by SimonBpvp** [JamminL/cata-classic-bugs#1059] opened 2024-04-29 15:59 UTC
![image](https://github.com/JamminL/cata-classic-bugs/assets/94299191/08383d85-2412-43a7-a3ac-ad9914246359)

scroll wheel doesn't scroll through glyphs, the slidey bar works if you drag it, but the arrow buttons and mouse scrolling doesn't work

**Comment by CharWS** [comment] 2024-04-29 16:01
duplicate of https://github.com/JamminL/cata-classic-bugs/issues/900

**Closed by CharWS** 2024-04-29 16:01 UTC
Labels: Pending Approval, CATACLYSM
