### ISSUE TITLE
[BUG] [Interface] Character informationS

### ISSUE THREAD

**Issue by SimonBpvp** [JamminL/cata-classic-bugs#1062] opened 2024-04-29 16:10 UTC
![image](https://github.com/JamminL/cata-classic-bugs/assets/94299191/ed53413d-f7e6-4a5a-959a-8d3e29a6e7a1)
![image](https://github.com/JamminL/cata-classic-bugs/assets/94299191/9177a6a8-3c06-4e09-808b-1e5385f28139)

the character information pane should stay extended if you close and reopen it
at the moment it will always default to closed when you reopen it

additionally it should remember if you have one section collapsed or expanded such as Melee or Ranged. And remember the positions of these
at the moment it will default to all expanded and in the default positioning if you close and reopen the pane.

**Comment by CharWS** [comment] 2024-04-29 16:11
duplicate of https://github.com/JamminL/cata-classic-bugs/issues/964

**Closed by CharWS** 2024-04-29 16:11 UTC
Labels: Pending Approval, CATACLYSM
